(function(){
'use strict';
const V3312='V3.3.12 Faster Evolutions + Interactive Campus';
const STAGES=['New Bond','Apprentice','Guardian','Ascendant','Celestial'];
const STAGE_SLUG=['new-bond','apprentice','guardian','ascendant','celestial'];
const STAGE_MIN=[1,3,5,8,12];
const TYPE_SLUG={luna:'velora',ember:'cascade',nova:'solstice',mallow:'aurelia',vesper:'vesper',briar:'briar',zephyr:'zephyr',prism:'prism',rook:'rook',solara:'solara'};
const REALM_ART={moonPalace:'assets/academy_hero.jpg',pearlCloud:'assets/majick_cosmos.jpg',celestialLibrary:'assets/room_library.jpg',roseNebula:'assets/majick_garden.jpg',starlightRooftop:'assets/majick_cosmos.jpg',dreamTemple:'assets/room_conservatory.jpg',midnightObservatory:'assets/room_observatory.jpg'};
const esc12=s=>{try{return esc(String(s??''))}catch(_){return String(s??'')}};
const canon12=t=>{try{return v338Canon(t)}catch(_){return (window.V338_CANON||{})[t]||null}};
const level12=p=>{try{return masPetLevel(p)}catch(_){return Math.max(1,Number(p?.level||1)||1)}};
const stageIndex12=p=>{const l=level12(p);return l>=12?4:l>=8?3:l>=5?2:l>=3?1:0};
const stageName12=p=>STAGES[stageIndex12(p)];
const typeSlug12=t=>TYPE_SLUG[t]||t;
const stageImage12=(t,i)=>`assets/familiars/evolution_stages/${typeSlug12(t)}-${STAGE_SLUG[i]}.webp`;
const currentImage12=p=>stageImage12(p?.type||'luna',stageIndex12(p));
window.v3312StageImage=stageImage12;
window.v3312CurrentGuardianImage=currentImage12;
function ensure3312(){S.v3311=S.v3311||{};S.v3311.schemaVersion=Math.max(1,Number(S.v3311.schemaVersion||1));S.v3311.grimoire=S.v3311.grimoire||{page:0,bookmarks:[],notes:{},remember:{},search:''};S.v3311.guardianEvolutionState=S.v3311.guardianEvolutionState||{};S.v3311.sanctuaryState=S.v3311.sanctuaryState||{bedAssignments:{}};S.v3311.collectionState=S.v3311.collectionState||{};for(const p of S.legacy?.pets||[]){const c=canon12(p.type);if(!c)continue;S.v3311.guardianEvolutionState[p.type]={displayName:c.display,level:level12(p),stage:stageName12(p),stageIndex:stageIndex12(p),image:currentImage12(p),updatedAt:Date.now()}}}
ensure3312();
const oldPortrait12=window.v334Portrait;
window.v334Portrait=function(p,variant='card'){if(!p||!canon12(p.type))return oldPortrait12?oldPortrait12(p,variant):'';const c=canon12(p.type),i=stageIndex12(p),name=c.display||p.name,src=stageImage12(p.type,i),fallback=c.portrait;const priority=(variant==='sidebar'||variant==='study')?'eager':'lazy';return `<div class="familiarPortrait ${variant} v3312StagePortrait" data-pet-type="${esc12(p.type)}" data-stage="${STAGE_SLUG[i]}" style="--pet-accent:${esc12(c.accent)}" title="${esc12(name)} • ${esc12(c.species)} • ${STAGES[i]}"><img src="${src}" data-fallback="${fallback}" loading="${priority}" decoding="async" ${priority==='eager'?'fetchpriority="high"':''} onerror="this.onerror=null;this.src=this.dataset.fallback" alt="${esc12(name)}, ${STAGES[i]} ${esc12(c.species)}"><span class="v3312StageBadge">${STAGES[i]}</span></div>`};
window.v3312CoachHTML=function(){if(!session||session.finished||!session.current||session.focus)return '';const p=activePet(),c=canon12(p.type),d=petDef(p),text=session.answered?(p.familiar?.lastSpeech||lfStudyReaction(p,session.chosen===session.current.answer,session.current)):petTip(session.current),m=typeof lfMood==='function'?lfMood(p):{icon:'✦',label:'Ready'};return `<div class="lfStudyBuddy unifiedStudyBuddy v3312Coach" style="--pet-accent:${esc12(c?.accent||'#b99cff')}"><div>${v334Portrait(p,'study')}</div><div class="lfBuddyText"><div class="familiarIdentityLine">${esc12(c?.sigil||'✦')} ${esc12(c?.title||'Guardian')} • ${stageName12(p)} • Level ${level12(p)}</div><b>${esc12(c?.display||p.name)} • ${m.icon} ${esc12(m.label)}</b><p>${esc12(text)}</p><div class="lfBuddyActions">${!session.answered?`<button class="btn ghost" onclick="usePetAbility()">✦ ${esc12(d.abilityName)}</button>`:''}<button class="btn ghost" onclick="navigate('companions')">Evolution tree</button></div></div></div>`};
window.petCoachHTML=window.v3312CoachHTML;window.lfPetCoachHTML=window.v3312CoachHTML;
window.v3312BootSanctuary=function(){const mount=document.getElementById('v3312SanctuaryMount');if(!mount||mount.dataset.booted==='1')return;mount.dataset.booted='1';mount.innerHTML=`<div class="v3312SanctuaryLoading"><b>Awakening the Living Sanctuary…</b><span>The original Phaser movement art is loading now.</span></div><iframe id="phase4SanctuaryFrame" class="phase4Frame" src="sanctuary/index.html?v=3312" title="Majick Studies Living Sanctuary" loading="eager" allow="fullscreen"></iframe>`};
window.phase4OpenFullscreen=function(){const f=document.getElementById('phase4SanctuaryFrame');if(f?.requestFullscreen)f.requestFullscreen().catch(()=>{});else{v3312BootSanctuary();setTimeout(()=>document.getElementById('phase4SanctuaryFrame')?.requestFullscreen?.().catch(()=>{}),450)}};
window.phase4SanctuaryHTML=function(){if(location.protocol==='file:')return `<section class="phase4Wrap"><div class="phase4Top"><div><b>✦ Phase 4 Living Sanctuary</b><br><span>Use the Majick launcher or GitHub Pages so Phaser can load.</span></div></div></section>`;return `<section class="phase4Wrap v3312PhaseWrap" aria-label="Phase 4 Living Sanctuary"><div class="phase4Top"><div><b>✦ Phase 4 Living Sanctuary</b><br><span>Velora, Cascade, Solstice, and Aurelia use your original protected movement art.</span></div><div class="phase4Actions"><button class="btn ghost" onclick="phase4OpenFullscreen()">Full Sanctuary</button><button class="btn primary" onclick="v3312BootSanctuary()">Enter Sanctuary</button></div></div><div id="v3312SanctuaryMount" class="v3312SanctuaryGate"><div class="v3312GateArt"><span>☾</span><h3>Dark Collegium Familiar Commons</h3><p>Click Enter Sanctuary when you want the moving Phaser world. The rest of the study app stays fast until then.</p><button class="btn violet" onclick="v3312BootSanctuary()">✦ Enter the Living Sanctuary</button></div></div><div class="phase4Help">Books → Living Grimoire • Desk → Study Now • Telescope → Observatory review • Guardians → evolution profiles • crystal beds → familiar rest • Apothecary → focus tools.</div></section>`};
window.v3312OpenEvolution=function(type){const c=canon12(type);if(!c)return;const p=(S.legacy?.pets||[]).find(x=>x.type===type),ci=p?stageIndex12(p):2;const modal=document.createElement('div');modal.className='v3312Modal';modal.innerHTML=`<div class="v3312ModalCard" style="--evo:${esc12(c.accent)}"><button class="v3312Close">×</button><div class="eyebrow">GUARDIAN EVOLUTION TREE</div><h2>${esc12(c.display)} • ${esc12(c.title)}</h2><p>${esc12(c.species)}${p?` • Level ${level12(p)} • ${STAGES[ci]}`:''}</p><div class="v3312Tree">${STAGES.map((s,i)=>`<article class="${i===ci?'current':''}"><img src="${stageImage12(type,i)}" loading="lazy" decoding="async" onerror="this.onerror=null;this.src='${c.portrait}'"><b>${s}</b><small>Level ${STAGE_MIN[i]}+</small></article>`).join('')}</div><div class="v3312BannerFold"><details><summary>View the original approved five-stage banner</summary><img src="${c.banner}" loading="lazy" decoding="async"></details></div></div>`;modal.addEventListener('click',e=>{if(e.target===modal||e.target.closest('.v3312Close'))modal.remove()});document.body.appendChild(modal)};
function evoCard12(type,p){const c=canon12(type);if(!c)return'';const ci=p?stageIndex12(p):2;return `<article class="v3312EvoCard" style="--evo:${esc12(c.accent)}"><img src="${p?stageImage12(type,ci):c.portrait}" loading="lazy" decoding="async" onerror="this.onerror=null;this.src='${c.portrait}'" alt="${esc12(c.display)}"><div><div class="eyebrow">${esc12(c.title)}</div><h3>${esc12(c.display)}</h3><p>${esc12(c.species)}${p?` • ${STAGES[ci]} • Lv ${level12(p)}`:' • Future bond'}</p><button class="btn ghost" onclick="v3312OpenEvolution('${esc12(type)}')">View 5 forms</button></div></article>`}
window.companionHTML=function(){const base=typeof lfCompanionHTML==='function'?lfCompanionHTML():'';const pets=S.legacy?.pets||[];const types=Object.keys(V338_CANON||{});return base+`<section class="v3312EvolutionWrap"><div class="sectionTitle"><div><h2>Guardian Evolution Gallery</h2><p>The picture now changes automatically with the Guardian's actual level. Only the current forms load here to keep the page fast.</p></div></div><div class="v3312EvoGrid">${types.map(t=>evoCard12(t,pets.find(p=>p.type===t))).join('')}</div></section>`};
window.realmGalleryHTML=function(){const L=S.legacy||{};return `<div class="sectionTitle"><div><h2>Magical Study Realms</h2><p>Study spaces now use actual Majick art instead of blank placeholder swatches.</p></div></div><div class="v3312RealmGallery">${Object.entries(V4_REALMS).map(([id,r])=>{const owned=(L.realms||[]).includes(id),active=L.activeRealm===id,art=REALM_ART[id]||'assets/academy_hero.jpg';return `<article class="v3312RealmCard ${owned?'':'locked'} ${active?'active':''}" onclick="realmAction('${id}')"><div class="v3312RealmPreview" style="background-image:linear-gradient(180deg,transparent 30%,rgba(10,4,15,.88)),url('${art}')"><span>${r.icon}</span><em>${!owned?'◆ '+r.cost:active?'ACTIVE':'OWNED'}</em></div><div class="v3312RealmCopy"><h3>${esc12(r.name)}</h3><p>${esc12(r.desc)}</p></div></article>`}).join('')}</div>`};
const oldVault12=window.vaultHTML;
window.vaultHTML=function(){try{const p=prog(),a=activePet(),c=canon12(a.type),img=currentImage12(a);return `<div class="sectionTitle"><div><h2>Moon Crystal Boutique & Magic Vault</h2><p>Rewards are earned by studying. No paid credits.</p></div><span class="rankBadge">◆ ${p.crystals||0} crystals</span></div><div class="v3312VaultHero"><div class="v3312VaultGuardian"><img src="${img}" onerror="this.onerror=null;this.src='${c.portrait}'" decoding="async"><div><div class="eyebrow">YOUR STUDY GUARDIAN</div><h3>${esc12(c.display)}</h3><p>${esc12(companionMessage())}</p><b>${stageName12(a)} • Level ${level12(a)}</b><div><button class="btn ghost" onclick="v3312OpenEvolution('${esc12(a.type)}')">Evolution tree</button><button class="btn violet" onclick="navigate('companions')">Companions</button></div></div></div><div class="v3312VaultChest"><span>🎁</span><h3>Crystal Chests</h3><p>Boss wins, mastery milestones, and long simulations can earn chests.</p><b>${p.chests||0} unopened</b><button class="btn violet" onclick="openChest()" ${p.chests?'':'disabled'}>Open one</button></div></div><div class="v3312ShopGrid">${SHOP.map(it=>{let owned=it.kind==='cosmetic'&&(p.cosmetics||[]).includes(it.id);return `<article class="v3312ShopItem ${owned?'owned':''}"><span>${it.icon}</span><h3>${esc12(it.name)}</h3><p>${esc12(it.desc)}</p><footer><b>◆ ${it.cost}</b><button class="btn ${owned?'good':'violet'}" onclick="buyShop('${esc12(it.id)}')" ${owned?'disabled':''}>${owned?'Owned':'Unlock'}</button></footer></article>`}).join('')}</div><div class="syncBox v3312Sync"><h3>Progress Sync & Backup</h3><p>Your existing XP, crystals, streaks, answers, course progress, and current Guardian records are preserved. New V3.3.12 fields remain additive.</p><button class="btn dark" onclick="exportSave()">Emergency Backup</button></div>`}catch(e){return oldVault12?oldVault12():''}};
const render12=window.render;window.render=function(){ensure3312();render12();const pill=document.querySelector('.top .pill');if(pill)pill.textContent='Living Familiars • V3.3.12 Faster Evolutions';document.title='Majick Studies — Faster Evolutions'};try{save();render()}catch(e){console.error('V3.3.12 boot',e)}
})();