(function(){
'use strict';
const ST=['New Bond','Apprentice','Guardian','Ascendant','Celestial'], SL=['new-bond','apprentice','guardian','ascendant','celestial'], MIN=[1,3,5,8,12];
const E=s=>{try{return esc(String(s??''))}catch(_){return String(s??'')}};
const C=t=>{try{return v338Canon(t)}catch(_){return (window.V338_CANON||{})[t]||null}};
const LV=p=>{try{return masPetLevel(p)}catch(_){return Number(p?.level||1)||1}};
const SI=p=>LV(p)>=12?4:LV(p)>=8?3:LV(p)>=5?2:LV(p)>=3?1:0;
const IMG=(t,i)=>`./assets/familiars/evolution_stages/${t}-${SL[i]}.webp`;
function V(){S.v3311=S.v3311||{};let v=S.v3311;v.schemaVersion=v.schemaVersion||1;v.grimoire=v.grimoire||{};v.grimoire.page=Number.isFinite(v.grimoire.page)?v.grimoire.page:0;v.grimoire.bookmarks=Array.isArray(v.grimoire.bookmarks)?v.grimoire.bookmarks:[];v.grimoire.notes=v.grimoire.notes||{};v.grimoire.remember=v.grimoire.remember||{};v.grimoire.search=v.grimoire.search||'';v.guardianEvolutionState=v.guardianEvolutionState||{};v.sanctuaryState=v.sanctuaryState||{bedAssignments:{}};v.sanctuaryState.bedAssignments=v.sanctuaryState.bedAssignments||{};v.collectionState=v.collectionState||{};v.lastSyncedAt=v.lastSyncedAt||null;return v}
function syncEvo(){let v=V();for(const p of S.legacy?.pets||[]){let c=C(p.type);if(c)v.guardianEvolutionState[p.type]={displayName:c.display,level:LV(p),stage:ST[SI(p)],stageIndex:SI(p),image:IMG(p.type,SI(p)),updatedAt:Date.now()}}}
V();syncEvo();
window.v3311StageImage=IMG;
window.v3311SetSearch=v=>{V().grimoire.search=String(v||'');save();render()};
window.v3311ToggleBookmark=id=>{let a=V().grimoire.bookmarks,i=a.indexOf(id);i>=0?a.splice(i,1):a.push(id);save();render()};
window.v3311ToggleRemember=id=>{let g=V().grimoire;g.remember[id]=!g.remember[id];save();render()};
window.v3311SaveNote=(id,v)=>{V().grimoire.notes[id]=String(v||'');save()};
function pages(){let c=course(),a=[{id:'cover',title:c.id+' Living Grimoire',sub:c.title,kind:'cover'}],s=c.studySections?.length?c.studySections:autoStudySections(c);s.forEach((x,i)=>a.push({id:'s'+i,title:x.title||`Chapter ${i+1}`,sub:x.summary||'',rows:x.rows||[],concepts:x.concepts||[],trap:x.trap||'',kind:'section'}));a.push({id:'mistakes',title:'Mistake Grimoire',sub:'Repair recent traps.',kind:'mistakes'},{id:'glossary',title:'Spellbook of Terms',sub:'Tap a term to reveal its meaning.',kind:'glossary',glossary:c.glossary||{}});return a}
function txt(p){let a=[p.title,p.sub,p.trap];(p.rows||[]).forEach(r=>a.push(...r));Object.entries(p.glossary||{}).forEach(([k,v])=>a.push(k,v));return a.filter(Boolean).join('. ')}
function hi(s){let x=E(s||'');for(const t of Object.keys(course().glossary||{}).sort((a,b)=>b.length-a.length).slice(0,60)){if(t.length<4)continue;try{x=x.replace(new RegExp(`\\b(${t.replace(/[.*+?^\${}()|[\\]\\\\]/g,'\\$&')})\\b`,'gi'),'<mark>$1</mark>')}catch(_){}}return x}
function quiz(p){let q=(course().questionBank||[]).find(x=>!p.concepts?.length||p.concepts.includes(x.topicId));if(!q)return'';return `<section class="v3311Mini"><b>${hi(cleanPrompt(q.prompt))}</b>${q.options.map((o,i)=>`<button onclick="v3311Mini('${E(q.id)}',${i},this)">${E(o)}</button>`).join('')}<div id="mq-${E(q.id)}"></div></section>`}
window.v3311Mini=(id,i,b)=>{let q=course().questionBank.find(x=>x.id===id),ok=q&&q.options[i]===q.answer,d=document.getElementById('mq-'+id);if(d)d.innerHTML=`<b class="${ok?'good':'bad'}">${ok?'✓ Correct':'Not quite'}</b><p>${ok?E(q.why||''):`Best answer: <b>${E(q.answer)}</b>. ${E(q.why||'')}`}</p>`;b?.parentElement?.querySelectorAll('button').forEach(x=>x.disabled=true)};
function body(p){if(p.kind==='cover')return'<div class="v3311CoverSigil">☾</div><p class="v3311Lead">Your free interactive WGU course book. No credits. No paywall.</p><div class="v3311Promise"><span>Page turns</span><span>Search</span><span>Bookmarks</span><span>Notes</span><span>Read aloud</span><span>Mini quizzes</span></div>';if(p.kind==='mistakes'){let r=(prog().answers||[]).slice(-80).filter(a=>!a.correct).slice(-8).reverse();return r.length?`<div class="v3311Mistakes">${r.map(a=>{let q=course().questionBank.find(x=>x.id===a.questionId);return q?`<article><b>${hi(cleanPrompt(q.prompt))}</b><span class="bad">You chose: ${E(a.chosen)}</span><span class="good">Best answer: ${E(q.answer)}</span><p>${hi(q.why||'')}</p></article>`:''}).join('')}</div>`:'<div class="v3311Empty">No recent repairs yet ✨</div>'}if(p.kind==='glossary')return`<div class="v3311Glossary">${Object.entries(p.glossary||{}).map(([k,v])=>`<details><summary>${E(k)}</summary><p>${hi(v)}</p></details>`).join('')}</div>`;return`<p class="v3311Lead">${hi(p.sub)}</p><div class="v3311Rows">${(p.rows||[]).map(r=>`<div><b>${hi(r[0])}</b><span>${hi(r[1])}</span>${r[2]?`<em>${hi(r[2])}</em>`:''}</div>`).join('')}</div>${p.trap?`<aside><b>WGU trap</b><span>${hi(p.trap)}</span></aside>`:''}${quiz(p)}`}
function book(){let g=V().grimoire,all=pages(),q=g.search.trim().toLowerCase(),ps=q?all.filter(p=>txt(p).toLowerCase().includes(q)):all;if(!ps.length)ps=all;let i=Math.max(0,Math.min(ps.length-1,g.page||0)),p=ps[i],k=course().id+':'+p.id,bm=g.bookmarks.includes(k),rm=!!g.remember[k];return`<section class="v3311BookShell"><header><div><div class="eyebrow">THE ARCANE STACKS • FREE EDITION</div><h2>Majick Living Grimoire</h2><p>Search, learn, annotate, practice and repair mistakes without leaving Majick Studies.</p></div><div class="v3311BookTools"><input value="${E(g.search)}" placeholder="Search this grimoire…"><button class="btn ghost" onclick="v3311SetSearch(this.previousElementSibling.value)">Search</button><button class="btn ghost" onclick="v3311SetSearch('')">Clear</button></div></header><div class="v3311BookStage"><button class="v3311Arrow" ${i?'':'disabled'} onclick="v3311SetPage(${i-1})">‹</button><article class="v3311Book ${p.kind==='cover'?'cover':''}"><div class="v3311Folio">${i+1} / ${ps.length}</div><div class="v3311PageActions"><button class="${bm?'active':''}" onclick="v3311ToggleBookmark('${E(k)}')">${bm?'★ Bookmarked':'☆ Bookmark'}</button><button class="${rm?'active':''}" onclick="v3311ToggleRemember('${E(k)}')">${rm?'✦ Remembered':'✧ Remember this'}</button></div><h3>${E(p.title)}</h3>${body(p)}<section class="v3311Notes"><label>Your margin notes</label><textarea onblur="v3311SaveNote('${E(k)}',this.value)" placeholder="Write a note to future-you…">${E(g.notes[k]||'')}</textarea></section><footer><button class="btn ghost" onclick='v3311Speak(${JSON.stringify(txt(p))})'>🔊 Read this page</button>${p.concepts?.length?`<button class="btn primary" onclick='practiceTopics(${JSON.stringify(p.concepts)})'>Practice this concept</button>`:''}</footer></article><button class="v3311Arrow" ${i===ps.length-1?'disabled':''} onclick="v3311SetPage(${i+1})">›</button></div><nav class="v3311Chapters">${ps.map((x,j)=>`<button class="${j===i?'active':''}" onclick="v3311SetPage(${j})">${E(x.title)}</button>`).join('')}</nav></section>`}
window.livingGrimoireHTML=book;
let oldScreen=window.screenHTML;window.screenHTML=function(){return S.screen==='livinggrimoire'?book():oldScreen()};
function evo(t,p){let c=C(t);if(!c)return'';let ci=p?SI(p):2;return`<section class="v3311Evolution" id="evo-${E(t)}" style="--evo:${E(c.accent)}"><div class="v3311EvoHead"><div><div class="eyebrow">EVOLUTION CODEX</div><h3>${E(c.display)} • ${E(c.title)}</h3><p>${E(c.species)}${p?` • Level ${LV(p)} • ${ST[ci]}`:''}</p></div><img src="${c.portrait}"></div><div class="v3311StageGrid">${ST.map((s,i)=>`<article class="${i===ci?'current':''}"><img src="${IMG(t,i)}"><b>${s}</b><small>Level ${MIN[i]}+</small></article>`).join('')}</div><img class="v3311FullBanner" src="${c.banner}"></section>`}
let oldComp=window.companionHTML;window.companionHTML=function(){let base=oldComp(),pets=S.legacy?.pets||[],focus=S.v3311GuardianFocus||'',types=Object.keys(V338_CANON||{}).sort((a,b)=>a===focus?-1:b===focus?1:0);return base+`<section class="v3311EvolutionWrap"><div class="sectionTitle"><div><h2>Guardian Evolution Codex</h2><p>Approved art, automatically matched to level.</p></div></div>${types.map(t=>evo(t,pets.find(p=>p.type===t))).join('')}</section>`};
let oldVault=window.vaultHTML;window.vaultHTML=function(){try{let p=prog(),a=activePet(),c=C(a.type);return`<div class="sectionTitle"><div><h2>Moon Crystal Boutique & Magic Vault</h2><p>Everything here is earned through studying.</p></div><span class="rankBadge">💎 ${p.crystals||0} crystals</span></div><div class="v3311VaultHero"><div class="v3311GuardianVault"><img src="${c?.portrait||''}"><div><div class="eyebrow">YOUR STUDY GUARDIAN</div><h3>${E(c?.display||a.name)}</h3><p>${E(companionMessage())}</p><p><b>${ST[SI(a)]}</b> • Level ${LV(a)}</p><button class="btn ghost" onclick="navigate('companions')">View evolution tree</button></div></div><div class="v3311Chest"><span>🎁</span><div><h3>Crystal Chests</h3><p>Earned from mastery and strong study sessions.</p><b>${p.chests||0} unopened</b><br><button class="btn violet" onclick="openChest()" ${p.chests?'':'disabled'}>Open one</button></div></div></div><div class="v3311ShopGrid">${SHOP.map(it=>{let o=it.kind==='cosmetic'&&(p.cosmetics||[]).includes(it.id);return`<article class="v3311ShopItem ${o?'owned':''}"><span>${it.icon}</span><h3>${E(it.name)}</h3><p>${E(it.desc)}</p><div><b>💎 ${it.cost}</b><button class="btn ${o?'good':'violet'}" onclick="buyShop('${E(it.id)}')" ${o?'disabled':''}>${o?'Owned':'Unlock'}</button></div></article>`}).join('')}</div><div class="syncBox v3311Sync"><h3>💾 Progress Sync & Backup</h3><p>XP, crystals, streaks, answers, course progress and Guardian data remain unchanged. V3.3.11 only adds optional new fields.</p><button class="btn dark" onclick="exportSave()">⬇ Emergency Backup</button></div>`}catch(err){return oldVault()}};
window.realmGalleryHTML=function(){let L=S.legacy;return`<div class="sectionTitle"><div><h2>Magical Study Realms</h2><p>Dark-fantasy college spaces instead of blank preview cards.</p></div></div><div class="v3311RealmGallery">${Object.entries(V4_REALMS).map(([id,r])=>{let o=L.realms.includes(id),a=L.activeRealm===id;return`<article class="v3311RealmCard ${o?'':'locked'} ${a?'active':''}" onclick="realmAction('${id}')"><div class="v3311RealmPreview realm-${id}"><span>${r.icon}</span></div><h3>${E(r.name)}</h3><p>${E(r.desc)}</p><em>${!o?'💎 '+r.cost:a?'ACTIVE':'OWNED'}</em></article>`}).join('')}</div>`};
window.addEventListener('message',ev=>{let d=ev.data||{};if(d.type==='MAJICK_OPEN_ROUTE_V3311'&&d.guardian){S.v3311GuardianFocus=d.guardian;save()}if(d.type==='MAJICK_BED_ASSIGN'&&d.bed&&d.guardian){V().sanctuaryState.bedAssignments[d.bed]=d.guardian;save()}});
window.v3311SyncEvolution=syncEvo;
})();